DROP TABLE IF EXISTS CYNAME;

CREATE TABLE CYNAME
(
    ID         VARCHAR(20) AUTO_INCREMENT PRIMARY KEY,
    CRUCHTNAME VARCHAR(30),
    CURRENCY   VARCHAR(30)
);

INSERT INTO CYNAME (CRUCHTNAME, CURRENCY)
VALUES ('英鎊', 'GBP'),
       ('歐元', 'EUR'),
       ('美金', 'USD'),
       ('測試', 'Test');
